name: youtube clone Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
    build:
      runs-on: self-hosted
      steps:
      
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            npm install

        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          with:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}




          
       
